private_subnet1_range    = "10.0.1.0/24" 
private_subnet2_range    = "10.0.2.0/24" 
private_subnet3_range    = "10.0.3.0/24" 
resource_group_name      = "dev"           #Precreate this while creating Backend Container 
security_group_name      = "sec_group1" 
vm1_computername         = "vm1" 
vm2_computername         = "vm2" 
vm3_computername         = "vm3" 
address_space            = "10.0.0.0/16" 
vnet_name                = "vnet1" 
location                 = "eastus" 
ssh_key                  = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVENqsAUMJg9NsmMRgZzp6ksZCafmNfqsNakvNLGMWp1MZ1NPTaU6T4kRXh+xobWiO3sSEoc1M8MEbJpBiP9WGZjFhWbhRSRY8hdmfGZ0iWn7M1xiOPk9fMS/dh+FTAm0Pdf7Jxa1mKafD7FtafpsTmV2eTl0TaGS9L1NTGOs0gSepoZutcsww6xaxXu8vp4VMvDFJi+ceQFPBBQE7rbAnRtcU0Jumwxi4VxMOcrLFbuqVj+sJo7nkSOwTEp+vJf8bQAcCwqdkMV8j2iAKTfX/p73R3g8rMfkGRJ6geZKFHM69X43Hfy+7ISYfMyEUKHBz/kZU4I1ZLqqghDos6mJb centos@ip-172-31-18-155.eu-west-2.compute.internal" 
environment              = "dev" 
storage_account          = "dev1safag"
 
#OS Information 
publisher                = "OpenLogic" 
offer                    = "CentOS" 
sku                      = "7.5" 
version                  = "latest" 
admin_username           = "centos" 
vm_size                  = "Standard_DS1_v2" 