resource_group_name                     =   "example-resources"
resource_group_name_location            =   "West Europe"
cluster_name                            =   "example-aks1"
vm_size                                 =   "Standard_D2_v2"
max_count                               =   "12"
min_count                               =   "3"
client_id                               =   ""    #add your appID from azure                                  
client_secret                           =   ""    #add your password from azure                                 
environment                             =   "Production"
node_pool_name                          =   "default"
kubernetes_version                      =   "1.15.10"
username                                =   "centos"